### PR TITLE
Create pycsw_wipe

### PR DESCRIPTION
**Pull request by rsignell-usgs**
added pycsw_wipe:  a command that wipes the database -- deletes all records

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
@kwilcox , if wondering why `pycsw_setup` doesn't accomplish the same thing, here's why:
```
root@fac968e58449:/opt/pycsw# pycsw_setup
Initializing static context
Creating database sqlite:////database/cite.db
Creating table spatial_ref_sys
(sqlite3.OperationalError) table spatial_ref_sys already exists [SQL: '\nCREATE TABLE spatial_ref_sys (\n\tsrid INTEGER NOT NULL, \n\tauth_name TEXT, \n\tauth_srid INTEGER, \n\tsrtext TEXT, \n\tPRIMARY KEY (srid)\n)\n\n']
ERROR: DB creation error.  Database tables already exist
Delete tables or database to reinitialize
Done
```

**Comment by kwilcox** [comment]
is `pycsw_wipe` executable?

**Comment by rsignell-usgs** [comment]
Wow, good catch.  No, it's not.   I added by using the editor on github, and I guess there is no way to change the filemode using the interface, right?

**Comment by rsignell-usgs** [comment]
@kwilcox , wait, DON'T MERGE yet.   Turns out there is a [Y/n] prompt that I have to figure out how to override.

**Comment by rsignell-usgs** [comment]
Okay, fixed now.

**Pull request merged**
